spring.mvc.pathmatch.matching-strategy=ant_path_matcher

spring.datasource.url=jdbc:postgresql://localhost:5432/${BP_DB_NAME:blueprints}
spring.datasource.username=${BP_DB_USER:blueprints_user}
spring.datasource.password=${BP_DB_PASSWORD:blueprints_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
server.port=8081
spring.profiles.active=default

